events {}

http {
  server {
    listen 8000;

    location = / {
      add_header Content-Type text/plain;
      return 200 "Supabase gateway activo. Usa /auth/v1, /rest/v1 o /storage/v1.";
    }

    location /auth/v1/ {
      proxy_pass http://supabase-auth:9999/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /rest/v1/ {
      proxy_pass http://supabase-rest:3000/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /storage/v1/ {
      proxy_pass http://supabase-storage:5000/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
