spring.application.name=Web

spring.datasource.url=jdbc:postgresql://192.168.35.99:5433/mourosub
spring.datasource.username=postgres
spring.datasource.password=KSbzz1YGpR5aYH7GMAwRTbD8XfQ7KjlLt1UPHfBrHEHNE7c9iotcRAPWN1jVBARP

spring.jpa.properties.hibernate.default_schema=public

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
