@startuml

title __REPOSITORY's Class Diagram__\n

  namespace com.mourosub.web {
    namespace repository {
      interface com.mourosub.web.repository.ActividadRepository {
      }
    }
  }
  

  namespace com.mourosub.web {
    namespace repository {
      interface com.mourosub.web.repository.AlquileresRepository {
      }
    }
  }
  

  namespace com.mourosub.web {
    namespace repository {
      interface com.mourosub.web.repository.CursoRepository {
      }
    }
  }
  

  namespace com.mourosub.web {
    namespace repository {
      interface com.mourosub.web.repository.InmersionRepository {
      }
    }
  }
  

  namespace com.mourosub.web {
    namespace repository {
      interface com.mourosub.web.repository.InstructorRepository {
      }
    }
  }
  

  namespace com.mourosub.web {
    namespace repository {
      interface com.mourosub.web.repository.MaterialRepository {
      }
    }
  }
  

  namespace com.mourosub.web {
    namespace repository {
      interface com.mourosub.web.repository.ReservaRepository {
          {abstract} + findByUsuario_IdUsuario()
      }
    }
  }
  

  namespace com.mourosub.web {
    namespace repository {
      interface com.mourosub.web.repository.SegurosRepository {
      }
    }
  }
  

  namespace com.mourosub.web {
    namespace repository {
      interface com.mourosub.web.repository.UsuarioRepository {
          {abstract} + findByEmail()
          {abstract} + findBySupabaseUserId()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
